project:
  type: website

website:
  title: "SALO Lab"
  site-url: "https://lluissalo.com"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: join.qmd
        text: Join
      - href: software.qmd
        text: Software
  page-footer:
    left: "SALO Lab — University of Tennessee, Knoxville"
    right:
      - text: "ORCID"
        href: "https://orcid.org/0000-0003-3339-538X"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false



